name: Application content change
description: Is your data different from ours? If so, please describe the differences so we can update it accordingly.
title: "Content Change To Application [ NAME ] needed."
labels: ["incorrect-app-info"]
assignees: []
body:
  - type: input
    id: application-name
    attributes:
      label: Application Name
      description: Enter the name of the application
      placeholder: ex. Google Chrome
    validations:
      required: true

  - type: input
    id: category-id
    attributes:
      label: Category Name
      description: Enter the category ID of the application
      placeholder: ex. development
    validations:
      required: false

  - type: input
    id: company
    attributes:
      label: Company
      description: Enter the company name
      placeholder: ex. Google
    validations:
      required: false

  - type: input
    id: app-url
    attributes:
      label: App URL
      description: Enter the URL of the application
      placeholder: ex. https://example.com
    validations:
      required: false

  - type: input
    id: comm-url
    attributes:
      label: Community URL
      description: Enter the URL of the community application
      placeholder: ex. https://example.com
    validations:
      required: false

  - type: input
    id: icon-url
    attributes:
      label: Icon URL
      description: Enter the URL of the application icon
      placeholder: ex. https://example.com/icon.png
    validations:
      required: false

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Enter tags for the application, separated by commas
      placeholder: ex. tag1, tag2, tag3
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Enter a description for the application
      placeholder: ex. This application is used for...
    validations:
      required: false

  - type: textarea
    id: tell-us
    attributes:
      label: Tell us more
      description: Provide additional information if needed
      placeholder: ex. Any additional details you'd like to share
    validations:
      required: false
