name: Feature request
title: "[Feature]: "
description: File a bug report.
assignees: []
body:
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to be added
      description: Please provide a detailed description of the feature request.
      placeholder: Describe the feature request here
    validations:
      required: true
